-- Production seed: no demo data inserted.
--
-- This file is intentionally empty so that `supabase db reset` on a fresh
-- deployment starts with a clean slate. All reference data (roles, report
-- definitions, label templates) is seeded by the migration itself.
--
-- For a development environment pre-loaded with sample warehouses, clients,
-- products, 180 pallets, orders, transfers, and demo users, run:
--
--   psql $DATABASE_URL -f supabase/seed.example.sql
--
-- The deployment_subscription table is also empty after a fresh deploy.
-- Activate a licence via the admin UI or by calling:
--
--   select public.record_licence_event('activated',
--     '{"plan":"professional","activated_by":"ops"}');
